intel/AiCSD

ms-web-ui/Dockerfile
ms-web-ui/package-lock.json

fix: updated socket.io-adapter

---

as-file-receiver-oem/Dockerfile
as-file-sender-gateway/Dockerfile
as-pipeline-sim/Dockerfile
as-pipeline-val/Dockerfile
as-task-launcher/Dockerfile
geti-pipeline/example_code/demo.py
geti-pipeline/example_code/requirements.txt
ms-data-organizer/Dockerfile
ms-file-receiver-gateway/Dockerfile
ms-file-sender-oem/Dockerfile
ms-file-watcher/Dockerfile
ms-job-repository/Dockerfile

- [ x] **_Commit Message meets guidelines as indicated in the URL\*_**
- Rebuid geti docker image: make docker-geti-pipeline
- Make run-geti
- Perform end-to-end testing with a geti model.

fix: update geti dependencies

---

ms-web-ui/package-lock.json

- [ x] **_Commit Message meets guidelines as indicated in the URL\*_**

fix: remove request package

---

ms-web-ui/package-lock.json
ms-web-ui/package.json

fix: removing codelyzer

---

ms-web-ui/package-lock.json

fix: dependabot vulnerabilities

---

.github/workflows/tests.yml

- [ x] **_Commit Message meets guidelines as indicated in the URL\*_**

fix: added apt update on github actions

---

ms-web-ui/package-lock.json

fix: vulnerabilities

---

ms-web-ui/package-lock.json

fix: dependabot issues

---

ms-web-ui/package-lock.json

fix: delete tough-cookie

---

as-file-receiver-oem/Dockerfile
as-file-sender-gateway/Dockerfile
as-pipeline-sim/Dockerfile
as-pipeline-val/Dockerfile
as-task-launcher/Dockerfile
ms-data-organizer/Dockerfile
ms-file-receiver-gateway/Dockerfile
ms-file-sender-oem/Dockerfile
ms-file-watcher/Dockerfile
ms-job-repository/Dockerfile

fix: updating ca-certificates version

---

.github/.hadolint.yaml
.github/workflows/reviewdog.yaml

- [Y] **_Commit Message meets guidelines as indicated in the URL\*_**

sdl: add hadolint

---

.github/.rdjson.jq
.github/.reviewdogConfig.yml
.github/workflows/codeql.yaml
.github/workflows/reviewdog.yaml

feat: add codeql scanning

---

Makefile
as-pipeline-grpc-go/Dockerfile
as-pipeline-grpc-go/LICENSE
as-pipeline-grpc-go/Makefile
as-pipeline-grpc-go/config/configuration.go
as-pipeline-grpc-go/controller/controller.go
as-pipeline-grpc-go/functions/functions.go
as-pipeline-grpc-go/main.go
as-pipeline-grpc-go/pkg/ovms/inferRequest.go
as-pipeline-grpc-go/pkg/ovms/inferResponse.go
as-pipeline-grpc-go/pkg/ovms/metadataRequest.go
as-pipeline-grpc-go/pkg/ovms/tensorOutput.go
as-pipeline-grpc-go/pkg/ovms/tensorOutput_test.go
as-pipeline-grpc-go/pkg/utilities/util.go
as-pipeline-grpc-go/pkg/yolov5/consts.go
as-pipeline-grpc-go/pkg/yolov5/detectedObject.go
as-pipeline-grpc-go/res/configuration.toml
docker-compose-edgex.yml
docker-compose-grpc-go.yml
go.mod
go.sum

1. add the Aicsd code as a submodule under retail-use-cases/use-cases
2. change directories to retail-use-cases
3. download models and sample media `make download-models download-sample-media`
4. build the ovms server `make build-ovms-server`
5. change directories to use-cases/aicsd
6. build the pipeline validator and pipeline grpc-go services `make docker-pipeline-val docker-pipeline-grpc-go`
7. modify docker-compose-pipeline-val.yml 
```
APPLICATIONSETTINGS_PIPELINEHOST: pipeline-grpc-go
APPLICATIONSETTINGS_PIPELINEPORT: 59790
```
8. run the pipeline validator and pipeline grpc-go services `make run-pipeline-grpc-go`
9. send a POST request to …

feat: add grpc-go pipeline service to work with the pipeline validator

---

.github/workflows/codeql.yaml
.github/workflows/gh-pages.yml
.github/workflows/reviewdog.yaml
.github/workflows/tests.yml

Fixes Token-Permissions Issues Identified By Scorecard

---

ms-file-receiver-gateway/controller/filehandler.go
ms-file-sender-oem/controller/filehandler.go

fix: resolving issues with codeQL

---

geti-pipeline/example_code/demo.py

- [x ] **_Commit Message meets guidelines as indicated in the URL\*_**
- [x ] Added labels (these are git labels such as bug or enhancement)
Issue Number
#95

fix: fix path expression

---

ms-file-sender-oem/controller/filehandler.go

fix: fixing codeQL path issue

---

docs_src/getting-started/system-setup.md

doc: update system-setup.md

---

.github/workflows/tests.yml
Makefile
ms-data-organizer/Makefile
ms-data-organizer/controller/controller_test.go
ms-file-receiver-gateway/Makefile
ms-file-receiver-gateway/controller/filehandler_test.go

feat: Add fuzz testing

---

.github/workflows/tests.yml
go.mod
go.sum

fix: reverting dependabot fixes

---

as-pipeline-sim/controller/controller.go
as-task-launcher/controller/controller.go

Fix: handling multiple images at once
